[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM15
monitor_port = COM15
build_flags =
  -D DDR001_CONTROL_FLOW_PIN=27
  -D DDR001_METER_UNDER_TEST_PIN=25
  -D DDR001_LED_PIN=2
  -D DDR001_LED_ACTIVE_LEVEL=HIGH
  -D DDR001_LED_ON_MS=120
  -D DDR001_DEBOUNCE_MS=40
  -D DDR001_PCNT_FILTER_CYCLES=1023
  -D DDR001_STABLE_LOW_US=17000
  -D DDR001_STABLE_HIGH_US=2000
