[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM15
monitor_port = COM15
build_flags =
  -D DDR001_PULSE_PIN=27
  -D DDR001_LED_PIN=2
  -D DDR001_LED_ACTIVE_LEVEL=HIGH
  -D DDR001_LED_ON_MS=120
  -D DDR001_DEBOUNCE_MS=40
