name: ddr001_diag_view_app
description: DDR001 Verificador Funcional offline field application.
publish_to: none
version: 1.6.0+18

environment:
  sdk: ^3.12.0

dependencies:
  camera: ^0.12.0+2
  crypto: ^3.0.7
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_markdown: ^0.7.7+1
  flutter_blue_plus: 1.36.8
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2
  google_mlkit_text_recognition: ^0.16.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image: ^4.9.1
  open_filex: ^4.7.0
  package_info_plus: ^9.0.1
  device_info_plus: ^11.5.0
  android_id: ^0.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.3
  printing: ^5.14.2
  share_plus: ^11.1.0
  shared_preferences: ^2.5.5
  uuid: ^4.5.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.34.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/manual/manual_de_uso.md
    - assets/branding/logo_symbol.png
    - assets/branding/splash_logo.png
    - assets/simulation/simulation_evidence_placeholder.png
    - assets/simulation/demo_meter_face.png

flutter_launcher_icons:
  android: true
  ios: false

  image_path: "assets/branding/app_icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/app_icon_foreground.png"

  min_sdk_android: 21
